### ISSUE TITLE
map build reproduceability

### ISSUE THREAD

**Issue by illwieckz** [UnvanquishedAssets/UnvanquishedAssets#2]
- [x] [_antares_](https://github.com/UnvanquishedAssets/map-antares_src.dpkdir)
- [x] [_chasm_](https://github.com/UnvanquishedAssets/map-chasm_src.dpkdir)
- [x] [_forlorn_](https://github.com/UnvanquishedAssets/map-forlorn_src.dpkdir)
- [x] [_parpax_](https://github.com/UnvanquishedAssets/map-parpax_src.dpkdir)
- [x] [_perseus_](https://github.com/UnvanquishedAssets/map-perseus_src.dpkdir)
- [x] [_plat23_](https://github.com/UnvanquishedAssets/map-plat23_src.dpkdir)
- [x] [_spacetracks_](https://github.com/UnvanquishedAssets/map-spacetracks_src.dpkdir)
- [x] [_station15_](https://github.com/UnvanquishedAssets/map-station15_src.dpkdir)
- [x] [_thunder_](https://github.com/UnvanquishedAssets/map-thunder_src.dpkdir)
- [x] [_vega_](https://github.com/UnvanquishedAssets/map-vega_src.dpkdir)
- [x] [_yocto_](https://github.com/UnvanquishedAssets/map-yocto_src.dpkdir)

**Comment by illwieckz** [comment]
So, _antares_ and _plat23_ build well and produce expected results, _thunder_ and _station15_ are now fixed.

**Comment by illwieckz** [comment]
I've build up a repository for _forlorn_ on my end (not yet uploaded), I'm looking for original pictures (lossless if possible) of:

```
textures/forlorn/display01_a.crn
textures/forlorn/display01_d.crn
textures/forlorn/display02_a.crn
textures/forlorn/display02_d.crn
textures/forlorn/display03_a.crn
textures/forlorn/display03_d.crn
meta/forlorn/forlorn.crn
```

By the way, the repository builds well and reproduces the original build.

**Comment by illwieckz** [comment]
The forlorn repository is now complete. Let's push the reproduceable map counter one digit further! :smiley:

**Comment by illwieckz** [comment]
Vega lightmap issue was caused by some preview textures. Now, only parpax is missing. 😊

**Comment by Viech** [comment]
Parpax should be there now!

**Comment by illwieckz** [comment]
Oh yes thanks! there is still that question about the template value in parpax map but that's not preventing to close that issue. Awesome!
