### ISSUE TITLE
'Mapper package' needed.

### ISSUE THREAD

**Issue by Viech** [UnvanquishedAssets/UnvanquishedAssets#4]
Since preview images were removed and netradiant and q3map2 do not yet support CRN textures upstream, mappers currently will not be able to continue working after the next Unvanquished release.

@illwieckz said he planned a package for mappers that contained all the textures in their original lossless format. This package would be used by netradiant and other map editors while Unvanquished loads the compressed textures instead. This package is needed soon, unless CRN support for netradiant and q3map2 is merged.

Personally I would be in favor of a single .dpk file to make updates easier (as the package needs to be kept in sync with Unvanquished releases by mappers).

**Comment by IngarKCT** [comment]
I consider the removal of the preview images to be the bug.

**Comment by illwieckz** [comment]
There is no need for ”Mapper package® anymore as both NetRadiant and q3map2 knows how to grok WebP and CRN.

See:

- WebP: https://gitlab.com/xonotic/netradiant/-/merge_requests/100
- CRN: https://gitlab.com/xonotic/netradiant/-/merge_requests/104
